<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./pusheen_vs_noodle.glb -t -T -P
Author: porgy (https://sketchfab.com/porgy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pusheen-vs-noodle-a510d532091247d3a9ef371edd6405aa
Title: Pusheen vs Noodle
-->

<script context="module" lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type ActionName = 'Animation'
  type GLTFResult = {
    nodes: {
      Object_10: THREE.Mesh
      Object_11: THREE.Mesh
      Object_12: THREE.Mesh
      Object_13: THREE.Mesh
      Object_15: THREE.Mesh
      Object_19: THREE.Mesh
      Object_20: THREE.Mesh
      Object_21: THREE.Mesh
      Object_23: THREE.Mesh
      Object_24: THREE.Mesh
      Object_26: THREE.Mesh
      Object_27: THREE.Mesh
      Object_31: THREE.Mesh
      Object_35: THREE.Mesh
      Object_49: THREE.Mesh
      Object_51: THREE.Mesh
      Object_53: THREE.Mesh
      Object_54: THREE.Mesh
      Object_56: THREE.Mesh
      Object_4: THREE.Mesh
      Object_5: THREE.Mesh
      Object_6: THREE.Mesh
      Object_8: THREE.Mesh
      Object_17: THREE.Mesh
      Object_29: THREE.Mesh
      Object_33: THREE.Mesh
      Object_37: THREE.Mesh
      Object_39: THREE.Mesh
      Object_41: THREE.Mesh
      Object_43: THREE.Mesh
      Object_45: THREE.Mesh
      Object_47: THREE.Mesh
    }
    materials: {
      vegetable: THREE.MeshBasicMaterial
      ['vegetable.001']: THREE.MeshBasicMaterial
      bowl1: THREE.MeshBasicMaterial
      ['vegetable.003']: THREE.MeshBasicMaterial
      pusheen: THREE.MeshBasicMaterial
      ['pusheen.001']: THREE.MeshBasicMaterial
      ['pusheen.002']: THREE.MeshBasicMaterial
      material: THREE.MeshBasicMaterial
      ['soup.001']: THREE.MeshBasicMaterial
      ['soup.003']: THREE.MeshBasicMaterial
      udon: THREE.MeshBasicMaterial
      ['Material.047']: THREE.MeshBasicMaterial
      ['Material.052']: THREE.MeshBasicMaterial
      bowl: THREE.MeshBasicMaterial
      soup: THREE.MeshBasicMaterial
      chopstick: THREE.MeshBasicMaterial
      ['soup.002']: THREE.MeshBasicMaterial
    }
  }

  const load = () => {
    return useGltf<GLTFResult>('/pusheen_vs_noodle-transformed.glb', { useDraco: true })
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  const gltf = load()
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="Cylinder_4" position={[-5.82, 1.47, 0.41]} scale={[0.19, 0.07, 0.19]}>
              <T.Mesh name="Object_10" geometry={gltf.nodes.Object_10.geometry} material={gltf.materials.vegetable} />
              <T.Mesh
                name="Object_11"
                geometry={gltf.nodes.Object_11.geometry}
                material={gltf.materials['vegetable.001']}
              />
              <T.Mesh name="Object_12" geometry={gltf.nodes.Object_12.geometry} material={gltf.materials.bowl1} />
              <T.Mesh
                name="Object_13"
                geometry={gltf.nodes.Object_13.geometry}
                material={gltf.materials['vegetable.003']}
              />
            </T.Group>
            <T.Group name="Cylinder001_5" position={[-5.45, 1.46, 0.87]} scale={[0.19, 0.06, 0.19]}>
              <T.Mesh name="Object_15" geometry={gltf.nodes.Object_15.geometry} material={gltf.materials.vegetable} />
            </T.Group>
            <T.Group name="Cylinder050_7" position={[-3.66, 1.98, -1.59]} rotation={[0.12, -0.41, 0.05]} scale={0.98}>
              <T.Mesh name="Object_19" geometry={gltf.nodes.Object_19.geometry} material={gltf.materials.pusheen} />
              <T.Mesh
                name="Object_20"
                geometry={gltf.nodes.Object_20.geometry}
                material={gltf.materials['pusheen.001']}
              />
              <T.Mesh
                name="Object_21"
                geometry={gltf.nodes.Object_21.geometry}
                material={gltf.materials['pusheen.002']}
              />
            </T.Group>
            <T.Group
              name="Sphere002_8"
              position={[-5.53, 1.55, -0.36]}
              rotation={[0.07, -0.77, 0.7]}
              scale={[0.6, 0.56, 0.6]}
            >
              <T.Mesh name="Object_23" geometry={gltf.nodes.Object_23.geometry} material={gltf.materials.bowl1} />
              <T.Mesh name="Object_24" geometry={gltf.nodes.Object_24.geometry} material={gltf.materials.material} />
            </T.Group>
            <T.Group name="Sphere003_9" position={[-4.86, 1.45, 0]} scale={[1.56, 0.65, 1.56]}>
              <T.Mesh name="Object_26" geometry={gltf.nodes.Object_26.geometry} material={gltf.materials['soup.001']} />
              <T.Mesh name="Object_27" geometry={gltf.nodes.Object_27.geometry} material={gltf.materials['soup.003']} />
            </T.Group>
            <T.Group
              name="BezierCurve_11"
              position={[-4.57, 0.93, -0.36]}
              rotation={[0, -0.56, -Math.PI]}
              scale={[1.42, 1.21, 1.42]}
            >
              <T.Mesh name="Object_31" geometry={gltf.nodes.Object_31.geometry} material={gltf.materials.udon} />
            </T.Group>
            <T.Group name="Cylinder005_13" position={[-4.04, 1.46, 0.28]} scale={[0.19, 0.06, 0.19]}>
              <T.Mesh name="Object_35" geometry={gltf.nodes.Object_35.geometry} material={gltf.materials.vegetable} />
            </T.Group>
            <T.Group name="Sphere004_20" position={[-4, 0.84, -1.38]} rotation={[1.95, -1.29, 0.25]} scale={0.95}>
              <T.Mesh name="Object_49" geometry={gltf.nodes.Object_49.geometry} material={gltf.materials.pusheen} />
            </T.Group>
            <T.Group name="Sphere005_21" position={[-3.69, 0.86, -1.16]} rotation={[1.16, -1.29, -0.57]} scale={0.95}>
              <T.Mesh name="Object_51" geometry={gltf.nodes.Object_51.geometry} material={gltf.materials.pusheen} />
            </T.Group>
            <T.Group name="Cylinder059_22" position={[-3.33, 0.64, -1.94]} rotation={[0, 0.54, -0.64]} scale={0.7}>
              <T.Mesh
                name="Object_53"
                geometry={gltf.nodes.Object_53.geometry}
                material={gltf.materials['Material.047']}
              />
              <T.Mesh
                name="Object_54"
                geometry={gltf.nodes.Object_54.geometry}
                material={gltf.materials['Material.052']}
              />
            </T.Group>
            <T.Group name="Cylinder003_23" position={[-3.79, 1.91, -1.41]} rotation={[0.21, -0.41, 0.08]} scale={1.22}>
              <T.Mesh
                name="Object_56"
                geometry={gltf.nodes.Object_56.geometry}
                material={gltf.materials['pusheen.001']}
              />
            </T.Group>
            <T.Group name="Sphere_2" position={[-4.86, 0.71, 0]} scale={[1.86, 1.67, 1.86]}>
              <T.Mesh name="Object_4" geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.bowl} />
              <T.Mesh name="Object_5" geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.bowl1} />
              <T.Mesh name="Object_6" geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.soup} />
            </T.Group>
            <T.Group name="Cube_3" position={[-4.17, 0.05, 1.18]} rotation={[0, 0.39, 0.01]} scale={[1.67, 0.08, 0.08]}>
              <T.Mesh name="Object_8" geometry={gltf.nodes.Object_8.geometry} material={gltf.materials.chopstick} />
            </T.Group>
            <T.Group name="Cylinder002_6" position={[-4.86, 1.42, -1.17]} scale={[0.14, 0.01, 0.14]}>
              <T.Mesh name="Object_17" geometry={gltf.nodes.Object_17.geometry} material={gltf.materials['soup.002']} />
            </T.Group>
            <T.Group name="Sphere010_10" position={[-4.11, 1.7, -1.45]} rotation={[2.96, -1.4, 1.49]} scale={0.95}>
              <T.Mesh name="Object_29" geometry={gltf.nodes.Object_29.geometry} material={gltf.materials.pusheen} />
            </T.Group>
            <T.Group name="Cylinder004_12" position={[-4.84, 1.43, 1.18]} scale={[0.1, 0.01, 0.1]}>
              <T.Mesh name="Object_33" geometry={gltf.nodes.Object_33.geometry} material={gltf.materials['soup.002']} />
            </T.Group>
            <T.Group name="Cylinder006_14" position={[-3.64, 1.43, 0.33]} scale={[0.14, 0.01, 0.14]}>
              <T.Mesh name="Object_37" geometry={gltf.nodes.Object_37.geometry} material={gltf.materials['soup.002']} />
            </T.Group>
            <T.Group name="Cylinder007_15" position={[-3.96, 1.43, 0.67]} scale={[0.11, 0.01, 0.11]}>
              <T.Mesh name="Object_39" geometry={gltf.nodes.Object_39.geometry} material={gltf.materials['soup.002']} />
            </T.Group>
            <T.Group name="Cylinder008_16" position={[-6.05, 1.43, -0.04]} scale={[0.16, 0.01, 0.16]}>
              <T.Mesh name="Object_41" geometry={gltf.nodes.Object_41.geometry} material={gltf.materials['soup.002']} />
            </T.Group>
            <T.Group name="Cylinder009_17" position={[-6.09, 1.43, 0.33]} scale={[0.11, 0.01, 0.11]}>
              <T.Mesh name="Object_43" geometry={gltf.nodes.Object_43.geometry} material={gltf.materials['soup.002']} />
            </T.Group>
            <T.Group
              name="Cube001_18"
              position={[-4, 0.05, 1.68]}
              rotation={[0, 0.33, 0.01]}
              scale={[1.67, 0.08, 0.08]}
            >
              <T.Mesh name="Object_45" geometry={gltf.nodes.Object_45.geometry} material={gltf.materials.chopstick} />
            </T.Group>
            <T.Group name="Sphere001_19" position={[-3.75, 1.7, -1.17]} rotation={[2.96, -1.4, 1.49]} scale={0.95}>
              <T.Mesh name="Object_47" geometry={gltf.nodes.Object_47.geometry} material={gltf.materials.pusheen} />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
